version: "3.9"
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - /usr/local/var/postgres:/var/lib/postgres
    ports:
      - 5432:5432